require("dotenv").config();
const connectDB = require("./config/db");
const User = require("./models/User");
const Club = require("./models/Club");

const recover = async () => {
  try {
    await connectDB();
    const clubs = await Club.find();
    console.log(`Scanning ${clubs.length} clubs for ownership mapping...`);

    let recovered = 0;

    for (const club of clubs) {
      // Look for the specific admin user generated by createClubAdmins.js
      const generatedAdmin = await User.findOne({ 
        clubId: club._id, 
        name: `${club.name} Admin` 
      });

      if (generatedAdmin) {
        // 1. Point the club's literal owner-pointer to this user
        club.adminId = generatedAdmin._id.toString();
        await club.save();

        // 2. Promote the user back to club_admin securing their state
        if (generatedAdmin.role !== "club_admin") {
          generatedAdmin.role = "club_admin";
          await generatedAdmin.save();
          console.log(`[RESTORED] ${club.name} -> ${generatedAdmin.email} is now Official Owner & club_admin.`);
          recovered++;
        } else {
          console.log(`[LINKED] ${club.name} -> ${generatedAdmin.email} was already club_admin, mapped ownership.`);
        }
      }
    }
    
    console.log(`\nSuccessfully recovered ownership mappings for ${recovered} clubs.`);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

recover();
